In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.5.1
3.0.3

## uplaod csv files

In [2]:
customers=pd.read_csv('customers.csv')
customers.head(5)

,CustomerID,Name,Gender,Age,City,Country,JoinDate,Email
0,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com
1,2,Customer 2,Male,26,Lahore,Pakistan,2024-12-12,customer2@mail.com
2,3,Customer 3,Male,55,Faisalabad,Pakistan,2024-01-17,customer3@mail.com
3,4,Customer 4,Male,23,Peshawar,Pakistan,2024-04-29,customer4@mail.com
4,5,Customer 5,Male,53,Peshawar,Pakistan,2024-11-28,customer5@mail.com

In [3]:
orders=pd.read_csv('orders.csv')
orders.head(5)

,OrderID,CustomerID,ProductID,OrderDate,Quantity,PaymentMethod,Status
0,1,274,320,2025-11-01,1,Cash,Completed
1,2,11,25,2025-08-02,1,Wallet,Completed
2,3,243,360,2025-04-16,2,Cash,Completed
3,4,340,267,2025-11-15,3,Card,Completed
4,5,317,61,2025-02-28,3,Cash,Completed

In [4]:
products=pd.read_csv('products.csv')
products.head(5)

   ProductID ProductName     Category  Brand  CostPrice  SellingPrice  Stock
0          1   Product 1         Home   Nova        481           642    211
1          2   Product 2         Home    Max        320           514    182
2          3   Product 3        Books    Eco        264           399    372
3          4   Product 4       Sports  Alpha        293           374    198
4          5   Product 5  Electronics    Eco        174           351    308

In [5]:
returns=pd.read_csv("returns.csv")
returns.head(5)

,ReturnID,OrderID,ProductID,ReturnDate,Reason,RefundAmount,Status
0,1,7,281,2025-04-17,Damaged,1854.84,Pending
1,2,9,119,2025-06-01,Damaged,1149.45,Pending
2,3,10,411,2025-08-07,Wrong Item,553.26,Pending
3,4,20,437,2025-03-26,Damaged,1830.46,Approved
4,5,24,423,2025-11-06,Late Delivery,213.61,Pending

In [6]:
sales=pd.read_csv('sales.csv')
sales.head(5)

   SaleID  OrderID  Revenue  Discount  Profit    Tax  ShippingCost
0       1        1       91      9.10   44.80   4.10             6
1       2        2      339     16.95  147.95  16.10             6
2       3        3     1230     61.50  250.07  58.43            16
3       4        4     1275     63.75  316.69  60.56             6
4       5        5      543     27.15  373.06  25.79             9

## clean dtasets

In [7]:
customers.dropna(inplace=True)

In [8]:
orders.dropna(inplace=True)

In [9]:
products.dropna(inplace=True)

In [10]:
returns.dropna(inplace=True)

In [11]:
sales.dropna(inplace=True)

In [12]:
print(type(customers))
print(type(orders))
print(type(products))
print(type(sales))
print(type(returns))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

## Merge datasets

In [13]:
final_data=pd.merge(
    customers,
    orders,
    on='CustomerID'
)

In [14]:
final_data=pd.merge(
    products,
    returns,
    on='ProductID'
)

In [15]:
final_data=pd.merge(
    final_data,
    sales,
    on='OrderID'
)
final_data.head(5)

,ProductID,ProductName,Category,Brand,CostPrice,SellingPrice,Stock,ReturnID,OrderID,ReturnDate,Reason,RefundAmount,Status,SaleID,Revenue,Discount,Profit,Tax,ShippingCost
0,5,Product 5,Electronics,Eco,174,351,308,164,687,2025-05-17,Damaged,240.45,Pending,687,351,35.1,122.11,15.79,4
1,7,Product 7,Books,Max,140,312,126,229,919,2025-06-04,Damaged,710.05,Approved,919,936,93.6,362.28,42.12,18
2,8,Product 8,Books,Eco,374,392,97,35,160,2025-05-22,Changed Mind,388.04,Approved,160,784,39.2,-50.44,37.24,10
3,10,Product 10,Clothing,Alpha,425,604,303,83,403,2025-08-09,Damaged,2005.02,Pending,403,2416,0.0,589.20,120.80,6
4,13,Product 13,Sports,Max,358,415,406,13,56,2025-06-19,Damaged,1489.20,Approved,56,1660,0.0,140.00,83.00,5

### check info/details

In [16]:
final_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     247 non-null    int64
 1   ProductName   247 non-null    str
 2   Category      247 non-null    str
 3   Brand         247 non-null    str
 4   CostPrice     247 non-null    int64
 5   SellingPrice  247 non-null    int64
 6   Stock         247 non-null    int64
 7   ReturnID      247 non-null    int64
 8   OrderID       247 non-null    int64
 9   ReturnDate    247 non-null    str
 10  Reason        247 non-null    str
 11  RefundAmount  247 non-null    float64
 12  Status        247 non-null    str
 13  SaleID        247 non-null    int64
 14  Revenue       247 non-null    int64
 15  Discount      247 non-null    float64
 16  Profit        247 non-null    float64
 17  Tax           247 non-null    float64
 18  ShippingCost  247 non-null    int64
dtypes: float64(4), int64(9), str(6)
memory usage: 36.8 KB

In [17]:
# check missing values

final_data.isnull().sum()

ProductID       0
ProductName     0
Category        0
Brand           0
CostPrice       0
SellingPrice    0
Stock           0
ReturnID        0
OrderID         0
ReturnDate      0
Reason          0
RefundAmount    0
Status          0
SaleID          0
Revenue         0
Discount        0
Profit          0
Tax             0
ShippingCost    0
dtype: int64

In [18]:
# check duplicated values
final_data.duplicated().sum()

np.int64(0)

In [19]:
final_data.columns

Index(['ProductID', 'ProductName', 'Category', 'Brand', 'CostPrice',
       'SellingPrice', 'Stock', 'ReturnID', 'OrderID', 'ReturnDate', 'Reason',
       'RefundAmount', 'Status', 'SaleID', 'Revenue', 'Discount', 'Profit',
       'Tax', 'ShippingCost'],
      dtype='str')