In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.5.1
3.0.3

## uplaod csv files

In [2]:
customers=pd.read_csv('customers.csv')
customers.head(5)

,CustomerID,Name,Gender,Age,City,Country,JoinDate,Email
0,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com
1,2,Customer 2,Male,26,Lahore,Pakistan,2024-12-12,customer2@mail.com
2,3,Customer 3,Male,55,Faisalabad,Pakistan,2024-01-17,customer3@mail.com
3,4,Customer 4,Male,23,Peshawar,Pakistan,2024-04-29,customer4@mail.com
4,5,Customer 5,Male,53,Peshawar,Pakistan,2024-11-28,customer5@mail.com

In [3]:
orders=pd.read_csv('orders.csv')
orders.head(5)

,OrderID,CustomerID,ProductID,OrderDate,Quantity,PaymentMethod,Status
0,1,274,320,2025-11-01,1,Cash,Completed
1,2,11,25,2025-08-02,1,Wallet,Completed
2,3,243,360,2025-04-16,2,Cash,Completed
3,4,340,267,2025-11-15,3,Card,Completed
4,5,317,61,2025-02-28,3,Cash,Completed

In [4]:
products=pd.read_csv('products.csv')
products.head(5)

   ProductID ProductName     Category  Brand  CostPrice  SellingPrice  Stock
0          1   Product 1         Home   Nova        481           642    211
1          2   Product 2         Home    Max        320           514    182
2          3   Product 3        Books    Eco        264           399    372
3          4   Product 4       Sports  Alpha        293           374    198
4          5   Product 5  Electronics    Eco        174           351    308

In [5]:
returns=pd.read_csv("returns.csv")
returns.head(5)

,ReturnID,OrderID,ProductID,ReturnDate,Reason,RefundAmount,Status
0,1,7,281,2025-04-17,Damaged,1854.84,Pending
1,2,9,119,2025-06-01,Damaged,1149.45,Pending
2,3,10,411,2025-08-07,Wrong Item,553.26,Pending
3,4,20,437,2025-03-26,Damaged,1830.46,Approved
4,5,24,423,2025-11-06,Late Delivery,213.61,Pending

In [6]:
sales=pd.read_csv('sales.csv')
sales.head(5)

   SaleID  OrderID  Revenue  Discount  Profit    Tax  ShippingCost
0       1        1       91      9.10   44.80   4.10             6
1       2        2      339     16.95  147.95  16.10             6
2       3        3     1230     61.50  250.07  58.43            16
3       4        4     1275     63.75  316.69  60.56             6
4       5        5      543     27.15  373.06  25.79             9

## clean dtasets

In [7]:
customers.dropna(inplace=True)

In [8]:
orders.dropna(inplace=True)

In [9]:
products.dropna(inplace=True)

In [10]:
returns.dropna(inplace=True)

In [11]:
sales.dropna(inplace=True)

In [12]:
print(type(customers))
print(type(orders))
print(type(products))
print(type(sales))
print(type(returns))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

## Merge datasets

In [13]:

final_data = customers.merge(
    orders,
    on="CustomerID",
    how="inner"
)

final_data = final_data.merge(
    sales,
    on="OrderID",
    how="inner"
)

final_data = final_data.merge(
    products,
    on="ProductID",
    how="inner"
)

final_data = final_data.merge(
    returns,
    on="ProductID",
    how="left"
)

print("Final dataset shape:", final_data.shape)

display(final_data.head())

Final dataset shape: (1197, 32)

,CustomerID,Name,Gender,Age,City,Country,JoinDate,Email,OrderID_x,ProductID,...,Brand,CostPrice,SellingPrice,Stock,ReturnID,OrderID_y,ReturnDate,Reason,RefundAmount,Status_y
0,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,24,423,...,Alpha,146,284,412,5.0,24.0,2025-11-06,Late Delivery,213.61,Pending
1,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,245,61,...,Nova,36,181,303,226.0,905.0,2025-02-13,Late Delivery,645.75,Approved
2,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,280,361,...,Nova,438,542,100,58.0,280.0,2025-07-03,Changed Mind,2191.19,Pending
3,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,682,50,...,Max,173,255,15,94.0,427.0,2025-06-26,Wrong Item,602.83,Pending
4,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,770,27,...,Max,108,250,366,NaN,NaN,NaN,NaN,NaN,NaN

### check info/details

In [14]:
final_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     1197 non-null   int64
 1   Name           1197 non-null   str
 2   Gender         1197 non-null   str
 3   Age            1197 non-null   int64
 4   City           1197 non-null   str
 5   Country        1197 non-null   str
 6   JoinDate       1197 non-null   str
 7   Email          1197 non-null   str
 8   OrderID_x      1197 non-null   int64
 9   ProductID      1197 non-null   int64
 10  OrderDate      1197 non-null   str
 11  Quantity       1197 non-null   int64
 12  PaymentMethod  1197 non-null   str
 13  Status_x       1197 non-null   str
 14  SaleID         1197 non-null   int64
 15  Revenue        1197 non-null   int64
 16  Discount       1197 non-null   float64
 17  Profit         1197 non-null   float64
 18  Tax            1197 non-null   float64
 19  ShippingCost   1197 non-null   int64
 20  ProductName    1197 non-null   str
 21  Category       1197 non-null   str
 22  Brand          1197 non-null   str
 23  CostPrice      1197 non-null   int64
 24  SellingPrice   1197 non-null   int64
 25  Stock          1197 non-null   int64
 26  ReturnID       741 non-null    float64
 27  OrderID_y      741 non-null    float64
 28  ReturnDate     741 non-null    str
 29  Reason         741 non-null    str
 30  RefundAmount   741 non-null    float64
 31  Status_y       741 non-null    str
dtypes: float64(6), int64(11), str(15)
memory usage: 447.6 KB

In [15]:
# check missing values

final_data.isnull().sum()

CustomerID         0
Name               0
Gender             0
Age                0
City               0
Country            0
JoinDate           0
Email              0
OrderID_x          0
ProductID          0
OrderDate          0
Quantity           0
PaymentMethod      0
Status_x           0
SaleID             0
Revenue            0
Discount           0
Profit             0
Tax                0
ShippingCost       0
ProductName        0
Category           0
Brand              0
CostPrice          0
SellingPrice       0
Stock              0
ReturnID         456
OrderID_y        456
ReturnDate       456
Reason           456
RefundAmount     456
Status_y         456
dtype: int64

In [16]:
# check duplicated values
final_data.duplicated().sum()

np.int64(0)

In [18]:
print(final_data.shape)
print(final_data.columns.tolist())

(1197, 32)
['CustomerID', 'Name', 'Gender', 'Age', 'City', 'Country', 'JoinDate', 'Email', 'OrderID_x', 'ProductID', 'OrderDate', 'Quantity', 'PaymentMethod', 'Status_x', 'SaleID', 'Revenue', 'Discount', 'Profit', 'Tax', 'ShippingCost', 'ProductName', 'Category', 'Brand', 'CostPrice', 'SellingPrice', 'Stock', 'ReturnID', 'OrderID_y', 'ReturnDate', 'Reason', 'RefundAmount', 'Status_y']

In [ ]:
# CLEAN DUPLICATE COLUMNS
final_data = final_data.rename(
    columns={
        "OrderID_x": "OrderID",
        "Status_x": "OrderStatus",
        "OrderID_y": "ReturnOrderID",
        "Status_y": "ReturnStatus"
    }
)

print(final_data.columns.tolist())

['CustomerID', 'Name', 'Gender', 'Age', 'City', 'Country', 'JoinDate', 'Email', 'OrderID', 'ProductID', 'OrderDate', 'Quantity', 'PaymentMethod', 'OrderStatus', 'SaleID', 'Revenue', 'Discount', 'Profit', 'Tax', 'ShippingCost', 'ProductName', 'Category', 'Brand', 'CostPrice', 'SellingPrice', 'Stock', 'ReturnID', 'ReturnOrderID', 'ReturnDate', 'Reason', 'RefundAmount', 'ReturnStatus']

In [19]:
final_data.head()

,CustomerID,Name,Gender,Age,City,Country,JoinDate,Email,OrderID_x,ProductID,...,Brand,CostPrice,SellingPrice,Stock,ReturnID,OrderID_y,ReturnDate,Reason,RefundAmount,Status_y
0,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,24,423,...,Alpha,146,284,412,5.0,24.0,2025-11-06,Late Delivery,213.61,Pending
1,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,245,61,...,Nova,36,181,303,226.0,905.0,2025-02-13,Late Delivery,645.75,Approved
2,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,280,361,...,Nova,438,542,100,58.0,280.0,2025-07-03,Changed Mind,2191.19,Pending
3,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,682,50,...,Max,173,255,15,94.0,427.0,2025-06-26,Wrong Item,602.83,Pending
4,1,Customer 1,Male,19,Quetta,Pakistan,2024-05-05,customer1@mail.com,770,27,...,Max,108,250,366,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
final_data.columns

Index(['CustomerID', 'Name', 'Gender', 'Age', 'City', 'Country', 'JoinDate',
       'Email', 'OrderID_x', 'ProductID', 'OrderDate', 'Quantity',
       'PaymentMethod', 'Status_x', 'SaleID', 'Revenue', 'Discount', 'Profit',
       'Tax', 'ShippingCost', 'ProductName', 'Category', 'Brand', 'CostPrice',
       'SellingPrice', 'Stock', 'ReturnID', 'OrderID_y', 'ReturnDate',
       'Reason', 'RefundAmount', 'Status_y'],
      dtype='str')

In [21]:
print("Total Revenue:", final_data["Revenue"].sum())
print("Total Profit:", final_data["Profit"].sum())
print("Total Orders:", final_data["OrderID"].nunique())
print("Total Products:", final_data["ProductID"].nunique())
print("Total Customers:", final_data["CustomerID"].nunique())
print("Total Refund:", final_data["RefundAmount"].sum())

Total Revenue: 1322734
Total Profit: 214433.38
Total Orders: 1000
Total Products: 427
Total Customers: 429
Total Refund: 550373.73

In [22]:
print(final_data["Category"].value_counts())

Category
Clothing       277
Electronics    267
Books          223
Sports         221
Home           209
Name: count, dtype: int64

In [23]:

# SAVE FINAL CLEAN DATASET

final_data.to_csv(
    "final_ecommerce_data.csv",
    index=False
)

print("Final dataset saved successfully!")

Final dataset saved successfully!

In [24]:
import os

print(os.path.abspath("final_ecommerce_data.csv"))
print(os.path.getsize("final_ecommerce_data.csv"), "bytes")

d:\01_Github repo folders\Ezitech internship projects\Sales Data_Analysis_Dashboard\final_ecommerce_data.csv
251201 bytes